name: Build Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: latest

    - name: Install dependencies
      run: |
        uv sync --extra dev
        uv pip install -e packages/pyspim
        uv pip install -e packages/napari-pyspim

    - name: Build documentation
      run: |
        uv run mkdocs build

    - name: Upload docs artifact
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: site/

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4

    - name: Download docs artifact
      uses: actions/download-artifact@v3
      with:
        name: docs
        path: site/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site 